version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tetris_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/script.sql
  authorization:
    build:
      context: Authorization/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: messenger
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVICE_PORT: 8080
  player_service:
    build:
      context: playerService/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: messenger
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVICE_PORT: 8081
  game_service:
    build:
      context: server/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:8082"
    environment:
      SERVICE_PORT: 8082
      
volumes:
  postgres-data: 